---
- name: Playbook - Install Apt apps    # metadata
  hosts: planetexpress:!farnsworth   # we want to take the planetexpress group and remove farnsworth
  connection: ssh     # default is to use the connection plugin ssh.py
  gather_facts: yes   # default is yes

  tasks:                             # a list of what we want to do 
  - name: using apt to install figlet  # metadata
    apt:                     # the module we want to run, apt.py
        name: 
         - figlet         # para\meter name has the value figlet
         - cowsay
         - bastet
        state: present       # parameter state has the value present
    become: yes              # elevate status to admin, sudo, enable, etc.

